<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Alumnos.UI.WinForms</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Alumnos.Aplicacion/Alumnos.Aplicacion.csproj" />
    <ProjectReference Include="../Alumnos.Infraestructura/Alumnos.Infraestructura.csproj" />
  </ItemGroup>
</Project>
